default: &default
  adapter: mysql2
  username: USER
  password: PASSWORD
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: trackme

test:
  <<: *default
  database: trackme

production:
  <<: *default
  database: trackme
